//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeStudiesApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeStudiesApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFA Time Study.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Step.
        /// </summary>
        internal static string BtnAddStep {
            get {
                return ResourceManager.GetString("BtnAddStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BtnBrowse {
            get {
                return ResourceManager.GetString("BtnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Copy.
        /// </summary>
        internal static string BtnCreateCopy {
            get {
                return ResourceManager.GetString("BtnCreateCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string BtnMoveDown {
            get {
                return ResourceManager.GetString("BtnMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string BtnMoveUp {
            get {
                return ResourceManager.GetString("BtnMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BtnOK {
            get {
                return ResourceManager.GetString("BtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string BtnPause {
            get {
                return ResourceManager.GetString("BtnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Step.
        /// </summary>
        internal static string BtnRemoveStep {
            get {
                return ResourceManager.GetString("BtnRemoveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        internal static string BtnStartRecording {
            get {
                return ResourceManager.GetString("BtnStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        internal static string BtnStopRecording {
            get {
                return ResourceManager.GetString("BtnStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string ColAverage {
            get {
                return ResourceManager.GetString("ColAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string ColCount {
            get {
                return ResourceManager.GetString("ColCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string ColDuration {
            get {
                return ResourceManager.GetString("ColDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (min).
        /// </summary>
        internal static string ColDurationMinutes {
            get {
                return ResourceManager.GetString("ColDurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (s).
        /// </summary>
        internal static string ColDurationSeconds {
            get {
                return ResourceManager.GetString("ColDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        internal static string ColSequence {
            get {
                return ResourceManager.GetString("ColSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string ColTimestamp {
            get {
                return ResourceManager.GetString("ColTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string ColTotal {
            get {
                return ResourceManager.GetString("ColTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string DimArea {
            get {
                return ResourceManager.GetString("DimArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string DimCount {
            get {
                return ResourceManager.GetString("DimCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string DimCustom {
            get {
                return ResourceManager.GetString("DimCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string DimLength {
            get {
                return ResourceManager.GetString("DimLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string DimVolume {
            get {
                return ResourceManager.GetString("DimVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string DimWeight {
            get {
                return ResourceManager.GetString("DimWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string FilterAllFiles {
            get {
                return ResourceManager.GetString("FilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Files (*.csv)|*.csv.
        /// </summary>
        internal static string FilterCsvFiles {
            get {
                return ResourceManager.GetString("FilterCsvFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Files (*.json)|*.json.
        /// </summary>
        internal static string FilterJsonFiles {
            get {
                return ResourceManager.GetString("FilterJsonFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Step.
        /// </summary>
        internal static string LblCurrentStep {
            get {
                return ResourceManager.GetString("LblCurrentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Step.
        /// </summary>
        internal static string LblDefaultStep {
            get {
                return ResourceManager.GetString("LblDefaultStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string LblDefaultValue {
            get {
                return ResourceManager.GetString("LblDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition Name.
        /// </summary>
        internal static string LblDefinitionName {
            get {
                return ResourceManager.GetString("LblDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        internal static string LblDimension {
            get {
                return ResourceManager.GetString("LblDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension Type.
        /// </summary>
        internal static string LblDimensionType {
            get {
                return ResourceManager.GetString("LblDimensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string LblDimensionUnit {
            get {
                return ResourceManager.GetString("LblDimensionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Count.
        /// </summary>
        internal static string LblEntryCount {
            get {
                return ResourceManager.GetString("LblEntryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string LblLocked {
            get {
                return ResourceManager.GetString("LblLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #.
        /// </summary>
        internal static string LblOrderNumber {
            get {
                return ResourceManager.GetString("LblOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Step.
        /// </summary>
        internal static string LblProcessStep {
            get {
                return ResourceManager.GetString("LblProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string LblProduct {
            get {
                return ResourceManager.GetString("LblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Time.
        /// </summary>
        internal static string LblProgressiveTime {
            get {
                return ResourceManager.GetString("LblProgressiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblRecordingStatus {
            get {
                return ResourceManager.GetString("LblRecordingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Time Study (CSV).
        /// </summary>
        internal static string MenuFileExportCsv {
            get {
                return ResourceManager.GetString("MenuFileExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Definition.
        /// </summary>
        internal static string MenuFileNew {
            get {
                return ResourceManager.GetString("MenuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Definition.
        /// </summary>
        internal static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Definition.
        /// </summary>
        internal static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Definition As....
        /// </summary>
        internal static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuToolsSettings {
            get {
                return ResourceManager.GetString("MenuToolsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string MsgConfirmDelete {
            get {
                return ResourceManager.GetString("MsgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the current recording?.
        /// </summary>
        internal static string MsgConfirmStop {
            get {
                return ResourceManager.GetString("MsgConfirmStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This definition is locked because recordings exist. Create a copy to edit..
        /// </summary>
        internal static string MsgDefinitionLocked {
            get {
                return ResourceManager.GetString("MsgDefinitionLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order numbers must be unique..
        /// </summary>
        internal static string MsgDuplicateOrderNumbers {
            get {
                return ResourceManager.GetString("MsgDuplicateOrderNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed successfully..
        /// </summary>
        internal static string MsgExportSuccess {
            get {
                return ResourceManager.GetString("MsgExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly one process step must be marked as default..
        /// </summary>
        internal static string MsgNoDefaultStep {
            get {
                return ResourceManager.GetString("MsgNoDefaultStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application for language changes to take effect..
        /// </summary>
        internal static string MsgRestartRequired {
            get {
                return ResourceManager.GetString("MsgRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition saved successfully..
        /// </summary>
        internal static string MsgSaveSuccess {
            get {
                return ResourceManager.GetString("MsgSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Save before closing?.
        /// </summary>
        internal static string MsgUnsavedChanges {
            get {
                return ResourceManager.GetString("MsgUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the following errors:.
        /// </summary>
        internal static string MsgValidationErrors {
            get {
                return ResourceManager.GetString("MsgValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-save recordings.
        /// </summary>
        internal static string SettingsAutoSave {
            get {
                return ResourceManager.GetString("SettingsAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Directory.
        /// </summary>
        internal static string SettingsBaseDir {
            get {
                return ResourceManager.GetString("SettingsBaseDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Size.
        /// </summary>
        internal static string SettingsButtonSize {
            get {
                return ResourceManager.GetString("SettingsButtonSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm before closing recording.
        /// </summary>
        internal static string SettingsConfirmClose {
            get {
                return ResourceManager.GetString("SettingsConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Delimiter.
        /// </summary>
        internal static string SettingsCsvDelimiter {
            get {
                return ResourceManager.GetString("SettingsCsvDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string StatusCompleted {
            get {
                return ResourceManager.GetString("StatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        internal static string StatusRecording {
            get {
                return ResourceManager.GetString("StatusRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About REFA Time Study.
        /// </summary>
        internal static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string TitleConfirm {
            get {
                return ResourceManager.GetString("TitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Copy.
        /// </summary>
        internal static string TitleCreateCopy {
            get {
                return ResourceManager.GetString("TitleCreateCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        internal static string TitleExportCsv {
            get {
                return ResourceManager.GetString("TitleExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TitleInformation {
            get {
                return ResourceManager.GetString("TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Definition.
        /// </summary>
        internal static string TitleOpenDefinition {
            get {
                return ResourceManager.GetString("TitleOpenDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Definition.
        /// </summary>
        internal static string TitleSaveDefinition {
            get {
                return ResourceManager.GetString("TitleSaveDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Base Directory.
        /// </summary>
        internal static string TitleSelectFolder {
            get {
                return ResourceManager.GetString("TitleSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition Editor.
        /// </summary>
        internal static string ViewDefinitionEditor {
            get {
                return ResourceManager.GetString("ViewDefinitionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Study Recording.
        /// </summary>
        internal static string ViewRecording {
            get {
                return ResourceManager.GetString("ViewRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Results.
        /// </summary>
        internal static string ViewResults {
            get {
                return ResourceManager.GetString("ViewResults", resourceCulture);
            }
        }
    }
}
