//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeStudiesApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeStudiesApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 All rights reserved..
        /// </summary>
        internal static string AboutCopyright {
            get {
                return ResourceManager.GetString("AboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Windows application for conducting REFA-style industrial time studies..
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About REFA Time Study.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFA Time Study.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BtnBrowse {
            get {
                return ResourceManager.GetString("BtnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Copy.
        /// </summary>
        internal static string BtnCreateCopy {
            get {
                return ResourceManager.GetString("BtnCreateCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string BtnMoveDown {
            get {
                return ResourceManager.GetString("BtnMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string BtnMoveUp {
            get {
                return ResourceManager.GetString("BtnMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string BtnPause {
            get {
                return ResourceManager.GetString("BtnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Default.
        /// </summary>
        internal static string BtnSetDefault {
            get {
                return ResourceManager.GetString("BtnSetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        internal static string BtnStartRecording {
            get {
                return ResourceManager.GetString("BtnStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        internal static string BtnStopRecording {
            get {
                return ResourceManager.GetString("BtnStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ColDefaultValue {
            get {
                return ResourceManager.GetString("ColDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColDescription {
            get {
                return ResourceManager.GetString("ColDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ColDimensionType {
            get {
                return ResourceManager.GetString("ColDimensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string ColDuration {
            get {
                return ResourceManager.GetString("ColDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Step.
        /// </summary>
        internal static string ColIsDefault {
            get {
                return ResourceManager.GetString("ColIsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #.
        /// </summary>
        internal static string ColOrderNumber {
            get {
                return ResourceManager.GetString("ColOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string ColProduct {
            get {
                return ResourceManager.GetString("ColProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive.
        /// </summary>
        internal static string ColProgressiveTime {
            get {
                return ResourceManager.GetString("ColProgressiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string ColTimestamp {
            get {
                return ResourceManager.GetString("ColTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string ColUnit {
            get {
                return ResourceManager.GetString("ColUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string DimArea {
            get {
                return ResourceManager.GetString("DimArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string DimCount {
            get {
                return ResourceManager.GetString("DimCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string DimCustom {
            get {
                return ResourceManager.GetString("DimCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string DimLength {
            get {
                return ResourceManager.GetString("DimLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string DimVolume {
            get {
                return ResourceManager.GetString("DimVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string DimWeight {
            get {
                return ResourceManager.GetString("DimWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Files (*.csv)|*.csv|All Files (*.*)|*.*.
        /// </summary>
        internal static string FilterCsvFiles {
            get {
                return ResourceManager.GetString("FilterCsvFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Files (*.json)|*.json|All Files (*.*)|*.*.
        /// </summary>
        internal static string FilterJsonFiles {
            get {
                return ResourceManager.GetString("FilterJsonFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Step.
        /// </summary>
        internal static string LblCurrentStep {
            get {
                return ResourceManager.GetString("LblCurrentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Step.
        /// </summary>
        internal static string LblDefaultStep {
            get {
                return ResourceManager.GetString("LblDefaultStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string LblDefaultValue {
            get {
                return ResourceManager.GetString("LblDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition Name.
        /// </summary>
        internal static string LblDefinitionName {
            get {
                return ResourceManager.GetString("LblDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        internal static string LblDimension {
            get {
                return ResourceManager.GetString("LblDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension Type.
        /// </summary>
        internal static string LblDimensionType {
            get {
                return ResourceManager.GetString("LblDimensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string LblDimensionUnit {
            get {
                return ResourceManager.GetString("LblDimensionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        internal static string LblEntryCount {
            get {
                return ResourceManager.GetString("LblEntryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #.
        /// </summary>
        internal static string LblOrderNumber {
            get {
                return ResourceManager.GetString("LblOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Step.
        /// </summary>
        internal static string LblProcessStep {
            get {
                return ResourceManager.GetString("LblProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Steps.
        /// </summary>
        internal static string LblProcessSteps {
            get {
                return ResourceManager.GetString("LblProcessSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string LblProduct {
            get {
                return ResourceManager.GetString("LblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Time.
        /// </summary>
        internal static string LblProgressiveTime {
            get {
                return ResourceManager.GetString("LblProgressiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string LblReady {
            get {
                return ResourceManager.GetString("LblReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        internal static string LblRecording {
            get {
                return ResourceManager.GetString("LblRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string LblStopped {
            get {
                return ResourceManager.GetString("LblStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export Time Study (CSV)....
        /// </summary>
        internal static string MenuFileExportCsv {
            get {
                return ResourceManager.GetString("MenuFileExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Definition.
        /// </summary>
        internal static string MenuFileNew {
            get {
                return ResourceManager.GetString("MenuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Definition....
        /// </summary>
        internal static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Definition.
        /// </summary>
        internal static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Definition &amp;As....
        /// </summary>
        internal static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Recording.
        /// </summary>
        internal static string MenuRecording {
            get {
                return ResourceManager.GetString("MenuRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause (Default Step).
        /// </summary>
        internal static string MenuRecordingPause {
            get {
                return ResourceManager.GetString("MenuRecordingPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start Recording.
        /// </summary>
        internal static string MenuRecordingStart {
            get {
                return ResourceManager.GetString("MenuRecordingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;top Recording.
        /// </summary>
        internal static string MenuRecordingStop {
            get {
                return ResourceManager.GetString("MenuRecordingStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings....
        /// </summary>
        internal static string MenuToolsSettings {
            get {
                return ResourceManager.GetString("MenuToolsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the current recording?.
        /// </summary>
        internal static string MsgConfirmStop {
            get {
                return ResourceManager.GetString("MsgConfirmStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This definition is locked because recordings exist. Create a copy to edit..
        /// </summary>
        internal static string MsgDefinitionLocked {
            get {
                return ResourceManager.GetString("MsgDefinitionLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording exported successfully..
        /// </summary>
        internal static string MsgExportSuccess {
            get {
                return ResourceManager.GetString("MsgExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No definition is loaded. Please create or open a definition first..
        /// </summary>
        internal static string MsgNoDefinitionLoaded {
            get {
                return ResourceManager.GetString("MsgNoDefinitionLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No completed recording to export..
        /// </summary>
        internal static string MsgNoRecordingToExport {
            get {
                return ResourceManager.GetString("MsgNoRecordingToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A recording is in progress. Stop the recording first..
        /// </summary>
        internal static string MsgRecordingInProgress {
            get {
                return ResourceManager.GetString("MsgRecordingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application for language changes to take effect..
        /// </summary>
        internal static string MsgRestartRequired {
            get {
                return ResourceManager.GetString("MsgRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition saved successfully..
        /// </summary>
        internal static string MsgSaveSuccess {
            get {
                return ResourceManager.GetString("MsgSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Save before closing?.
        /// </summary>
        internal static string MsgUnsavedChanges {
            get {
                return ResourceManager.GetString("MsgUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the following errors:.
        /// </summary>
        internal static string MsgValidationErrors {
            get {
                return ResourceManager.GetString("MsgValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-save recordings.
        /// </summary>
        internal static string SettingsAutoSave {
            get {
                return ResourceManager.GetString("SettingsAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Directory.
        /// </summary>
        internal static string SettingsBaseDir {
            get {
                return ResourceManager.GetString("SettingsBaseDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Size.
        /// </summary>
        internal static string SettingsButtonSize {
            get {
                return ResourceManager.GetString("SettingsButtonSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm before stopping recording.
        /// </summary>
        internal static string SettingsConfirmStop {
            get {
                return ResourceManager.GetString("SettingsConfirmStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Delimiter.
        /// </summary>
        internal static string SettingsCsvDelimiter {
            get {
                return ResourceManager.GetString("SettingsCsvDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string SettingsExport {
            get {
                return ResourceManager.GetString("SettingsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string SettingsRecording {
            get {
                return ResourceManager.GetString("SettingsRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string TitleConfirm {
            get {
                return ResourceManager.GetString("TitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Copy.
        /// </summary>
        internal static string TitleCreateCopy {
            get {
                return ResourceManager.GetString("TitleCreateCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        internal static string TitleExportCsv {
            get {
                return ResourceManager.GetString("TitleExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TitleInfo {
            get {
                return ResourceManager.GetString("TitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Definition.
        /// </summary>
        internal static string TitleOpenDefinition {
            get {
                return ResourceManager.GetString("TitleOpenDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Definition.
        /// </summary>
        internal static string TitleSaveDefinition {
            get {
                return ResourceManager.GetString("TitleSaveDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Base Directory.
        /// </summary>
        internal static string TitleSelectFolder {
            get {
                return ResourceManager.GetString("TitleSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV (Ctrl+E).
        /// </summary>
        internal static string ToolTipExport {
            get {
                return ResourceManager.GetString("ToolTipExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Definition (Ctrl+N).
        /// </summary>
        internal static string ToolTipNew {
            get {
                return ResourceManager.GetString("ToolTipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Definition (Ctrl+O).
        /// </summary>
        internal static string ToolTipOpen {
            get {
                return ResourceManager.GetString("ToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Definition (Ctrl+S).
        /// </summary>
        internal static string ToolTipSave {
            get {
                return ResourceManager.GetString("ToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording (F5).
        /// </summary>
        internal static string ToolTipStartRecording {
            get {
                return ResourceManager.GetString("ToolTipStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording (F6).
        /// </summary>
        internal static string ToolTipStopRecording {
            get {
                return ResourceManager.GetString("ToolTipStopRecording", resourceCulture);
            }
        }
    }
}
