//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeStudiesApp.Properties;

using System.Globalization;
using System.Resources;

/// <summary>
/// A strongly-typed resource class for looking up localized strings.
/// </summary>
internal static class Resources
{
    private static ResourceManager? _resourceManager;

    /// <summary>
    /// Returns the cached ResourceManager instance used by this class.
    /// </summary>
    public static ResourceManager ResourceManager
    {
        get
        {
            _resourceManager ??= new ResourceManager(
                "TimeStudiesApp.Properties.Resources",
                typeof(Resources).Assembly);

            return _resourceManager;
        }
    }

    /// <summary>
    /// Overrides the current thread's CurrentUICulture property for all
    /// resource lookups using this strongly typed resource class.
    /// </summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>
    /// Gets a localized string for the given key.
    /// </summary>
    private static string GetString(string name) =>
        ResourceManager.GetString(name, Culture) ?? name;

    // Application Title
    public static string AppTitle => GetString("AppTitle");

    // Menu: File
    public static string MenuFile => GetString("MenuFile");
    public static string MenuFileNew => GetString("MenuFileNew");
    public static string MenuFileOpen => GetString("MenuFileOpen");
    public static string MenuFileSave => GetString("MenuFileSave");
    public static string MenuFileSaveAs => GetString("MenuFileSaveAs");
    public static string MenuFileExportCsv => GetString("MenuFileExportCsv");
    public static string MenuFileExit => GetString("MenuFileExit");

    // Menu: Tools
    public static string MenuTools => GetString("MenuTools");
    public static string MenuToolsSettings => GetString("MenuToolsSettings");

    // Menu: Help
    public static string MenuHelp => GetString("MenuHelp");
    public static string MenuHelpAbout => GetString("MenuHelpAbout");

    // Toolbar
    public static string ToolbarNew => GetString("ToolbarNew");
    public static string ToolbarOpen => GetString("ToolbarOpen");
    public static string ToolbarSave => GetString("ToolbarSave");
    public static string ToolbarExport => GetString("ToolbarExport");

    // Recording Controls
    public static string BtnStartRecording => GetString("BtnStartRecording");
    public static string BtnStopRecording => GetString("BtnStopRecording");
    public static string BtnPause => GetString("BtnPause");

    // Labels
    public static string LblProgressiveTime => GetString("LblProgressiveTime");
    public static string LblCurrentStep => GetString("LblCurrentStep");
    public static string LblDefinitionName => GetString("LblDefinitionName");
    public static string LblDescription => GetString("LblDescription");
    public static string LblOrderNumber => GetString("LblOrderNumber");
    public static string LblProcessStep => GetString("LblProcessStep");
    public static string LblDefaultStep => GetString("LblDefaultStep");
    public static string LblProduct => GetString("LblProduct");
    public static string LblDimension => GetString("LblDimension");
    public static string LblDimensionType => GetString("LblDimensionType");
    public static string LblDimensionUnit => GetString("LblDimensionUnit");
    public static string LblDefaultValue => GetString("LblDefaultValue");
    public static string LblEntryCount => GetString("LblEntryCount");
    public static string LblCreatedAt => GetString("LblCreatedAt");
    public static string LblModifiedAt => GetString("LblModifiedAt");
    public static string LblLocked => GetString("LblLocked");
    public static string LblYes => GetString("LblYes");
    public static string LblNo => GetString("LblNo");

    // Dimension Types
    public static string DimWeight => GetString("DimWeight");
    public static string DimCount => GetString("DimCount");
    public static string DimLength => GetString("DimLength");
    public static string DimArea => GetString("DimArea");
    public static string DimVolume => GetString("DimVolume");
    public static string DimCustom => GetString("DimCustom");

    // Settings Dialog
    public static string SettingsTitle => GetString("SettingsTitle");
    public static string SettingsLanguage => GetString("SettingsLanguage");
    public static string SettingsBaseDir => GetString("SettingsBaseDir");
    public static string SettingsButtonSize => GetString("SettingsButtonSize");
    public static string SettingsAutoSave => GetString("SettingsAutoSave");
    public static string SettingsConfirmClose => GetString("SettingsConfirmClose");
    public static string SettingsCsvDelimiter => GetString("SettingsCsvDelimiter");
    public static string SettingsGeneral => GetString("SettingsGeneral");
    public static string SettingsRecording => GetString("SettingsRecording");
    public static string SettingsExport => GetString("SettingsExport");

    // About Dialog
    public static string AboutTitle => GetString("AboutTitle");
    public static string AboutVersion => GetString("AboutVersion");
    public static string AboutDescription => GetString("AboutDescription");

    // Messages
    public static string MsgDefinitionLocked => GetString("MsgDefinitionLocked");
    public static string MsgConfirmStop => GetString("MsgConfirmStop");
    public static string MsgUnsavedChanges => GetString("MsgUnsavedChanges");
    public static string MsgRestartRequired => GetString("MsgRestartRequired");
    public static string MsgConfirmExit => GetString("MsgConfirmExit");
    public static string MsgRecordingInProgress => GetString("MsgRecordingInProgress");
    public static string MsgNoDefinitionSelected => GetString("MsgNoDefinitionSelected");
    public static string MsgSaveSuccessful => GetString("MsgSaveSuccessful");
    public static string MsgExportSuccessful => GetString("MsgExportSuccessful");
    public static string MsgNoRecordingsToExport => GetString("MsgNoRecordingsToExport");

    // Titles
    public static string TitleCreateCopy => GetString("TitleCreateCopy");
    public static string TitleSelectFolder => GetString("TitleSelectFolder");
    public static string TitleConfirmation => GetString("TitleConfirmation");
    public static string TitleWarning => GetString("TitleWarning");
    public static string TitleError => GetString("TitleError");
    public static string TitleInformation => GetString("TitleInformation");
    public static string TitleOpenDefinition => GetString("TitleOpenDefinition");
    public static string TitleSaveDefinition => GetString("TitleSaveDefinition");
    public static string TitleExportCsv => GetString("TitleExportCsv");

    // Buttons
    public static string BtnOK => GetString("BtnOK");
    public static string BtnCancel => GetString("BtnCancel");
    public static string BtnBrowse => GetString("BtnBrowse");
    public static string BtnAddStep => GetString("BtnAddStep");
    public static string BtnRemoveStep => GetString("BtnRemoveStep");
    public static string BtnMoveUp => GetString("BtnMoveUp");
    public static string BtnMoveDown => GetString("BtnMoveDown");
    public static string BtnSetAsDefault => GetString("BtnSetAsDefault");
    public static string BtnCreateCopy => GetString("BtnCreateCopy");

    // Views
    public static string ViewDefinitionEditor => GetString("ViewDefinitionEditor");
    public static string ViewRecording => GetString("ViewRecording");
    public static string ViewResults => GetString("ViewResults");

    // Status Messages
    public static string StatusReady => GetString("StatusReady");
    public static string StatusRecording => GetString("StatusRecording");
    public static string StatusPaused => GetString("StatusPaused");

    // File Filters
    public static string FilterDefinitionFiles => GetString("FilterDefinitionFiles");
    public static string FilterCsvFiles => GetString("FilterCsvFiles");

    // CSV Export Headers
    public static string CsvHeaderDefinition => GetString("CsvHeaderDefinition");
    public static string CsvHeaderRecordingId => GetString("CsvHeaderRecordingId");
    public static string CsvHeaderStartedAt => GetString("CsvHeaderStartedAt");
    public static string CsvHeaderCompletedAt => GetString("CsvHeaderCompletedAt");
    public static string CsvHeaderSeq => GetString("CsvHeaderSeq");
    public static string CsvHeaderTimestamp => GetString("CsvHeaderTimestamp");
    public static string CsvHeaderDurationSec => GetString("CsvHeaderDurationSec");
    public static string CsvHeaderDurationMin => GetString("CsvHeaderDurationMin");
    public static string CsvHeaderDimensionValue => GetString("CsvHeaderDimensionValue");
    public static string CsvHeaderCount => GetString("CsvHeaderCount");
    public static string CsvHeaderTotalDurationSec => GetString("CsvHeaderTotalDurationSec");
    public static string CsvHeaderTotalDurationMin => GetString("CsvHeaderTotalDurationMin");
    public static string CsvHeaderAvgDurationSec => GetString("CsvHeaderAvgDurationSec");
    public static string CsvHeaderSummary => GetString("CsvHeaderSummary");
}
